FROM php:8.4-fpm-alpine

ARG USER
ARG USER_ID
ARG GROUP_ID

# Update & install system deps
RUN apk update && apk add --no-cache \
    git \
    zip \
    unzip \
    curl \
    libzip-dev \
    libpng-dev \
    libxml2-dev \
    icu-dev \
    oniguruma-dev \
    bash \
    mysql-client \
    postgresql-client \
    postgresql-dev \
    nginx \
    supervisor

# Install PHP extensions
RUN docker-php-ext-configure intl \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql intl mbstring xml

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Create user
RUN addgroup -g $GROUP_ID $USER
RUN adduser -D -u $USER_ID -G $USER -s /bin/bash $USER

WORKDIR /var/www
USER $USER
